/**
 * This class was generated by the VisualAge for Java Access Bean SmartGuide.
 * Warning:  Modifications will be lost when this part is regenerated.
 */

package com.hps.july.persistence;


public interface LeasePaymentAccessBeanData {



    public java.math.BigDecimal getSumRub() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setSumRub( java.math.BigDecimal newValue );
    public java.lang.String getPaymentstate() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setPaymentstate( java.lang.String newValue );
    public java.math.BigDecimal getNdsRub() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setNdsRub( java.math.BigDecimal newValue );
    public java.lang.Integer getCreatedby() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setCreatedby( java.lang.Integer newValue );
    public java.math.BigDecimal getRurremainder() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setRurremainder( java.math.BigDecimal newValue );
    public boolean getByautorur() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setByautorur( boolean newValue );
    public java.sql.Date getEnddate() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setEnddate( java.sql.Date newValue );
    public com.hps.july.persistence.CurrencyKey getCurrencyKey() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public java.lang.String getOfficememonumber() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setOfficememonumber( java.lang.String newValue );
    public java.sql.Timestamp getCreated() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setCreated( java.sql.Timestamp newValue );
    public java.math.BigDecimal getPayrate() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setPayrate( java.math.BigDecimal newValue );
    public java.lang.Integer getModifiedby() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setModifiedby( java.lang.Integer newValue );
    public java.sql.Date getDate() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setDate( java.sql.Date newValue );
    public com.hps.july.persistence.LeaseDocumentKey getActKey() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public com.hps.july.persistence.LeaseRuleKey getLeaseRuleKey() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public java.lang.Integer getOtvworker() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setOtvworker( java.lang.Integer newValue );
    public java.lang.String getDocposvid() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setDocposvid( java.lang.String newValue );
    public java.lang.String getIsSchetFakt() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setIsSchetFakt( java.lang.String newValue );
    public java.lang.Integer getOperator() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setOperator( java.lang.Integer newValue );
    public java.lang.Integer getWillbeinact() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setWillbeinact( java.lang.Integer newValue );
    public java.lang.String getPaymentType() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setPaymentType( java.lang.String newValue );
    public java.sql.Date getBegindate() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setBegindate( java.sql.Date newValue );
    public java.math.BigDecimal getSumnds() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setSumnds( java.math.BigDecimal newValue );
    public java.lang.String getDocNumber() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setDocNumber( java.lang.String newValue );
    public java.sql.Timestamp getModified() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setModified( java.sql.Timestamp newValue );
    public com.hps.july.persistence.ResourceKey getResourceKey() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public java.math.BigDecimal getSumm() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setSumm( java.math.BigDecimal newValue );
    public int getLeaseDocPosition() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setLeaseDocPosition( int newValue );
    public java.lang.Integer getUsedinact() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setUsedinact( java.lang.Integer newValue );
    public com.hps.july.persistence.LeaseDocumentKey getLeaseContractKey() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public java.lang.String getSource() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
    public void setSource( java.lang.String newValue );

	/**
	 * getFlagOplNds
	 * @generated
	 */
	public java.lang.Boolean getFlagOplNds() throws java.rmi.RemoteException, javax.ejb.CreateException, javax.ejb.FinderException, javax.naming.NamingException;
	/**
	 * setFlagOplNds
	 * @generated
	 */
	public void setFlagOplNds(java.lang.Boolean newValue);
}
