package com.hps.july.persistence;

import java.rmi.RemoteException;
import java.security.Identity;
import java.util.Properties;
import javax.ejb.*;
/**
 * This is an Entity Bean class with CMP fields
 * Данные PIE -связь мест хранения NRI и Platinum
 */
public class PIEMxranLinkBean implements EntityBean {
	private javax.ejb.EntityContext entityContext = null;
	public int mxrannri;
	private final static long serialVersionUID = 3206093459760846163L;
	public java.lang.String mxranplatinum_mxranplatinum;
	public java.lang.Integer mxranplatinum_owner_organization;
	private transient com.ibm.ivj.ejb.associations.interfaces.SingleLink mxranplatinumLink = null;
/**
 * This method was generated by the VisualAge for Java EJB AccessBean tool.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public java.util.Hashtable _copyFromEJB() {
        com.ibm.ivj.ejb.runtime.AccessBeanHashtable h = new com.ibm.ivj.ejb.runtime.AccessBeanHashtable();

        h.put("mxrannri", new Integer(getMxrannri()));
        h.put("mxranplatinumKey", getMxranplatinumKey());
        h.put("__Key", getEntityContext().getPrimaryKey());

        return h;

}
/**
 * This method was generated by the VisualAge for Java EJB AccessBean tool.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void _copyToEJB(java.util.Hashtable h) {


}
/**
 * This method was generated for supporting the associations.
 * @return java.util.Vector
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected java.util.Vector _getLinks() {
	java.util.Vector links = new java.util.Vector();
	links.addElement(getMxranplatinumLink());
	return links;
}
/**
 * This method was generated for supporting the associations.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected void _initLinks() {
	mxranplatinumLink = null;
}
/**
 * This method was generated for supporting the associations.
 * @exception java.rmi.RemoteException The exception description.
 * @exception javax.ejb.RemoveException The exception description.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected void _removeLinks() throws java.rmi.RemoteException, javax.ejb.RemoveException {
	java.util.Enumeration links = _getLinks().elements();
	while (links.hasMoreElements()) {
		try {
			((com.ibm.ivj.ejb.associations.interfaces.Link) (links.nextElement())).remove();
		}
		catch (javax.ejb.FinderException e) {} //Consume Finder error since I am going away
	}
}
/**
 * ejbActivate method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbActivate() throws java.rmi.RemoteException {
	_initLinks();
}
/**
 * ejbCreate method for a CMP entity bean
 * @param argMxrannri int
 * @exception javax.ejb.CreateException The exception description.
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbCreate(int argMxrannri, int argOwner, String argMxranplatinum) throws javax.ejb.CreateException, java.rmi.RemoteException {
	_initLinks();
	// All CMP fields should be initialized here.
	mxrannri = argMxrannri;
	mxranplatinum_owner_organization = new Integer(argOwner);
	mxranplatinum_mxranplatinum = argMxranplatinum;
}
/**
 * ejbLoad method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbLoad() throws java.rmi.RemoteException {
	_initLinks();
}
/**
 * ejbPassivate method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbPassivate() throws java.rmi.RemoteException {}
/**
 * ejbPostCreate method for a CMP entity bean
 * @param argMxrannri int
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbPostCreate(int argMxrannri) throws java.rmi.RemoteException {}
/**
 * ejbRemove method comment
 * @exception java.rmi.RemoteException The exception description.
 * @exception javax.ejb.RemoveException The exception description.
 */
public void ejbRemove() throws java.rmi.RemoteException, javax.ejb.RemoveException {
	_removeLinks();
}
/**
 * ejbStore method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbStore() throws java.rmi.RemoteException {}
/**
 * getEntityContext method comment
 * @return javax.ejb.EntityContext
 */
public javax.ejb.EntityContext getEntityContext() {
	return entityContext;
}
/**
 * Insert the method's description here.
 * Creation date: (18.12.2002 17:39:26)
 * @return int
 */
public int getMxrannri() {
	return mxrannri;
}
/**
 * This method was generated for supporting the association named PIEMxranLink2mxran.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public com.hps.july.persistence.PIEMxranPlatinum getMxranplatinum() throws java.rmi.RemoteException, javax.ejb.FinderException {
	return (com.hps.july.persistence.PIEMxranPlatinum)this.getMxranplatinumLink().value();
}
/**
 * This method was generated for supporting the association named PIEMxranLink2mxran.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public com.hps.july.persistence.PIEMxranPlatinumKey getMxranplatinumKey() {
	com.hps.july.persistence.PIEMxranPlatinumKey temp = null;
	temp = new com.hps.july.persistence.PIEMxranPlatinumKey();
	boolean mxranplatinum_NULLTEST = true;
	mxranplatinum_NULLTEST &= (mxranplatinum_mxranplatinum == null);
	temp.mxranplatinum = mxranplatinum_mxranplatinum;
	mxranplatinum_NULLTEST &= (mxranplatinum_owner_organization == null);
	temp.owner_organization = mxranplatinum_owner_organization;
	if (mxranplatinum_NULLTEST) temp = null;
	return temp;
}
/**
 * This method was generated for supporting the association named PIEMxranLink2mxran.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected com.ibm.ivj.ejb.associations.interfaces.SingleLink getMxranplatinumLink() {
	if (mxranplatinumLink == null)
		mxranplatinumLink = new PIEMxranLinkToMxranplatinumLink(this);
	return mxranplatinumLink;
}
/**
 * This method was generated for supporting the association named PIEMxranLink2mxran.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void privateSetMxranplatinumKey(com.hps.july.persistence.PIEMxranPlatinumKey inKey) {
	boolean mxranplatinum_NULLTEST = (inKey == null);
	if (mxranplatinum_NULLTEST) mxranplatinum_mxranplatinum = null; else mxranplatinum_mxranplatinum = inKey.mxranplatinum;
	if (mxranplatinum_NULLTEST) mxranplatinum_owner_organization = null; else mxranplatinum_owner_organization = inKey.owner_organization;
}
/**
 * setEntityContext method comment
 * @param ctx javax.ejb.EntityContext
 * @exception java.rmi.RemoteException The exception description.
 */
public void setEntityContext(javax.ejb.EntityContext ctx) throws java.rmi.RemoteException {
	entityContext = ctx;
}
/**
 * This method was generated for supporting the association named PIEMxranLink2mxran.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void setMxranplatinum(com.hps.july.persistence.PIEMxranPlatinum aMxranplatinum) throws java.rmi.RemoteException {
	this.getMxranplatinumLink().set(aMxranplatinum);
}
/**
 * unsetEntityContext method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void unsetEntityContext() throws java.rmi.RemoteException {
	entityContext = null;
}
}
