package com.hps.july.persistence;

import java.rmi.RemoteException;
import java.security.Identity;
import java.util.Properties;
import javax.ejb.*;
/**
 * This is an Entity Bean class with CMP fields
 * Группировки для поиска организаций
 */
public class SearchGrouppingBean implements EntityBean {
	private javax.ejb.EntityContext entityContext = null;
	public String name;
	public int searchGroupping;
	private final static long serialVersionUID = 3206093459760846163L;
	public java.lang.Integer searchGroup_searchgroup;
	private transient com.ibm.ivj.ejb.associations.interfaces.SingleLink searchGroupLink = null;
	private transient com.ibm.ivj.ejb.associations.interfaces.ManyLink searchesLink = null;
/**
 * This method was generated by the VisualAge for Java EJB AccessBean tool.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public java.util.Hashtable _copyFromEJB() {
        com.ibm.ivj.ejb.runtime.AccessBeanHashtable h = new com.ibm.ivj.ejb.runtime.AccessBeanHashtable();

        h.put("searchGroupping", new Integer(getSearchGroupping()));
        h.put("searchGroupKey", getSearchGroupKey());
        h.put("name", getName());
        h.put("__Key", getEntityContext().getPrimaryKey());

        return h;

}
/**
 * This method was generated by the VisualAge for Java EJB AccessBean tool.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void _copyToEJB(java.util.Hashtable h) {
        Integer localSearchGroupping = (Integer) h.get("searchGroupping");
        java.lang.String localName = (java.lang.String) h.get("name");

        if ( h.containsKey("searchGroupping") )
            setSearchGroupping((localSearchGroupping).intValue());
        if ( h.containsKey("name") )
            setName((localName));

}
/**
 * This method was generated for supporting the associations.
 * @return java.util.Vector
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected java.util.Vector _getLinks() {
	java.util.Vector links = new java.util.Vector();
	links.addElement(getSearchGroupLink());
	links.addElement(getSearchesLink());
	return links;
}
/**
 * This method was generated for supporting the associations.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected void _initLinks() {
	searchGroupLink = null;
	searchesLink = null;
}
/**
 * This method was generated for supporting the associations.
 * @exception java.rmi.RemoteException The exception description.
 * @exception javax.ejb.RemoveException The exception description.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected void _removeLinks() throws java.rmi.RemoteException, javax.ejb.RemoveException {
	java.util.Enumeration links = _getLinks().elements();
	while (links.hasMoreElements()) {
		try {
			((com.ibm.ivj.ejb.associations.interfaces.Link) (links.nextElement())).remove();
		}
		catch (javax.ejb.FinderException e) {} //Consume Finder error since I am going away
	}
}
/**
 * This method was generated for supporting the association named Searches2Groupping.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void addSearches(com.hps.july.persistence.Searches aSearches) throws java.rmi.RemoteException {
	this.getSearchesLink().addElement(aSearches);
}
/**
 * ejbActivate method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbActivate() throws java.rmi.RemoteException {
	_initLinks();
}
/**
 * ejbCreate method for a CMP entity bean
 * @param argSearchGroupping int
 * @exception javax.ejb.CreateException The exception description.
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbCreate(int argSearchGroupping) throws javax.ejb.CreateException, java.rmi.RemoteException {
	_initLinks();
	// All CMP fields should be initialized here.
	searchGroupping = argSearchGroupping;
}
/**
 * ejbCreate method for a CMP entity bean
 * @param argSearchGroupping int
 * @exception javax.ejb.CreateException The exception description.
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbCreate(int argSearchGroupping, Integer argGroup, String argName ) throws javax.ejb.CreateException, java.rmi.RemoteException {
	_initLinks();
	// All CMP fields should be initialized here.
	searchGroupping = argSearchGroupping;
	searchGroup_searchgroup = argGroup;
	name = argName;
}
/**
 * ejbLoad method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbLoad() throws java.rmi.RemoteException {
	_initLinks();
}
/**
 * ejbPassivate method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbPassivate() throws java.rmi.RemoteException {}
/**
 * ejbPostCreate method for a CMP entity bean
 * @param argSearchGroupping int
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbPostCreate(int argSearchGroupping) throws java.rmi.RemoteException {}
/**
 * ejbRemove method comment
 * @exception java.rmi.RemoteException The exception description.
 * @exception javax.ejb.RemoveException The exception description.
 */
public void ejbRemove() throws java.rmi.RemoteException, javax.ejb.RemoveException {
	_removeLinks();
}
/**
 * ejbStore method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbStore() throws java.rmi.RemoteException {}
/**
 * getEntityContext method comment
 * @return javax.ejb.EntityContext
 */
public javax.ejb.EntityContext getEntityContext() {
	return entityContext;
}
/**
 * Getter method for name
 * @return java.lang.String
 */
public java.lang.String getName() {
	return name;
}
/**
 * This method was generated for supporting the association named Searches2Groupping.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public java.util.Enumeration getSearches() throws java.rmi.RemoteException, javax.ejb.FinderException {
	return this.getSearchesLink().enumerationValue();
}
/**
 * This method was generated for supporting the association named Searches2Groupping.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected com.ibm.ivj.ejb.associations.interfaces.ManyLink getSearchesLink() {
	if (searchesLink == null)
		searchesLink = new SearchGrouppingToSearchesLink(this);
	return searchesLink;
}
/**
 * This method was generated for supporting the association named SearchGroupping2Group.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public com.hps.july.persistence.SearchGroup getSearchGroup() throws java.rmi.RemoteException, javax.ejb.FinderException {
	return (com.hps.july.persistence.SearchGroup)this.getSearchGroupLink().value();
}
/**
 * This method was generated for supporting the association named SearchGroupping2Group.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public com.hps.july.persistence.SearchGroupKey getSearchGroupKey() {
	com.hps.july.persistence.SearchGroupKey temp = null;
	temp = new com.hps.july.persistence.SearchGroupKey();
	boolean searchGroup_NULLTEST = true;
	searchGroup_NULLTEST &= (searchGroup_searchgroup == null);
	temp.searchgroup = ((searchGroup_searchgroup == null) ? 0 : searchGroup_searchgroup.intValue());
	if (searchGroup_NULLTEST) temp = null;
	return temp;
}
/**
 * This method was generated for supporting the association named SearchGroupping2Group.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected com.ibm.ivj.ejb.associations.interfaces.SingleLink getSearchGroupLink() {
	if (searchGroupLink == null)
		searchGroupLink = new SearchGrouppingToSearchGroupLink(this);
	return searchGroupLink;
}
/**
 * Insert the method's description here.
 * Creation date: (10.06.2002 11:06:56)
 * @return int
 */
public int getSearchGroupping() {
	return searchGroupping;
}
/**
 * This method was generated for supporting the association named SearchGroupping2Group.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void privateSetSearchGroupKey(com.hps.july.persistence.SearchGroupKey inKey) {
	boolean searchGroup_NULLTEST = (inKey == null);
	if (searchGroup_NULLTEST) searchGroup_searchgroup = null; else searchGroup_searchgroup = (new Integer(inKey.searchgroup));
}
/**
 * This method was generated for supporting the association named Searches2Groupping.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void secondaryAddSearches(com.hps.july.persistence.Searches aSearches) {
	this.getSearchesLink().secondaryAddElement(aSearches);
}
/**
 * This method was generated for supporting the association named Searches2Groupping.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void secondaryRemoveSearches(com.hps.july.persistence.Searches aSearches) {
	this.getSearchesLink().secondaryRemoveElement(aSearches);
}
/**
 * This method was generated for supporting the association named SearchGroupping2Group.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void secondarySetSearchGroup(com.hps.july.persistence.SearchGroup aSearchGroup) throws java.rmi.RemoteException {
	this.getSearchGroupLink().secondarySet(aSearchGroup);
}
/**
 * setEntityContext method comment
 * @param ctx javax.ejb.EntityContext
 * @exception java.rmi.RemoteException The exception description.
 */
public void setEntityContext(javax.ejb.EntityContext ctx) throws java.rmi.RemoteException {
	entityContext = ctx;
}
/**
 * Setter method for name
 * @param newValue java.lang.String
 */
public void setName(java.lang.String newValue) {
	this.name = newValue;
}
/**
 * This method was generated for supporting the association named SearchGroupping2Group.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void setSearchGroup(com.hps.july.persistence.SearchGroup aSearchGroup) throws java.rmi.RemoteException {
	this.getSearchGroupLink().set(aSearchGroup);
}
/**
 * Insert the method's description here.
 * Creation date: (10.06.2002 11:06:56)
 * @param newSearchGroupping int
 */
public void setSearchGroupping(int newSearchGroupping) {
	searchGroupping = newSearchGroupping;
}
/**
 * unsetEntityContext method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void unsetEntityContext() throws java.rmi.RemoteException {
	entityContext = null;
}
}
