package com.hps.july.arenda;

/**
 * Констатны состояния модуля-приложения "Аренда"
 * Creation date: (27.06.2002 10:49:50)
 * @author: Sergey Gourov
 */
public interface APPStates {
	int UNDER_CONSTRACTION_REP1 = -1000;
	int UNDER_CONSTRACTION_REP2 = -1001;

	int MAIN = 1;
	int LOGIN = 2;
	int LOGOUT = 3;

	int WE_ARENDA_LIST = 4; 
	int WE_ARENDA_EDIT = 5;
	int ARENDA_POS_LIST = 6;
	int ARENDA_POS_EDIT = 7;
	int CHARGE_RULES_LIST = 8;
	int CHARGE_RULE_EDIT = 9;
	int PAY_RULES_LIST = 10;
	int PAY_RULE_EDIT = 11;

	int US_ARENDA_LIST = 12;
	int US_ARENDA_EDIT = 13;

	int CHANNEL_ARENDA_LIST = 14;
	int CHANNEL_ARENDA_EDIT = 15;

	//int USER_ARENDA_LIST		= 16;
	//int USER_ARENDA_EDIT		= 17;

	int MUTUAL_REGLMNTS_LIST = 18;

	//int MUTUAL_REGLMNT_LIST	= 19;

	int ORG_LOOKUP = 20;
	int WORKER_LOOKUP = 21;
	int POS_LOOKUP = 22;
	int GROUP_LOOKUP = 23;
	int GROUPPING_LOOKUP = 24;

	int RESOURCE_LOOKUP = 25;
	int RESTYPE_LOOKUP = 26;
	int RESSBTYPE_LOOKUP = 27;

	int MAINPARAMS_MUTREGLMNT_EDIT = 28;

	int PHONES_MUTREGLMNT_LIST = 29;
	int PHONE_MUTREGLMNT_EDIT = 30;

	int CONTRACTS_MUTREGLMNT_LIST = 31;
	int CONTRACT_MUTREGLMNT_EDIT = 32;

	int MUTUAL_RULES_LIST = 33;
	int MUTUAL_RULE_EDIT = 34;

	int CONTRACT_LOOKUP = 35;
	int ACCOUNT_LOOKUP = 36;

	int CHARGES_LIST = 37;
	int CHARGE_EDIT = 38;

	int PAYMENTS_LIST = 39;
	int PAYMENT_EDIT = 40;

	int MUTACTS_LIST = 41;
	int MUTACT_EDIT = 42;

	int STATE_WEARENDA_EDIT = 43;
	int STATE_USARENDA_EDIT = 44;
	int STATE_CHANNELARENDA_EDIT = 45;

	int HISTORY_LIST = 46;
	int HISTORY_FORM = 47;

	int HISTORY_PAYMENTS_LIST = 48;
	int HISTORY_PAYMENT_EDIT = 49;

	int HISTORY_CHARGES_LIST = 50;
	int HISTORY_CHARGE_EDIT = 51;

	int HISTORY_ARENDA_POS_LIST = 52;
	int HISTORY_ARENDA_POS_EDIT = 53;

	int HISTORY_CHARGE_RULES_LIST = 54;
	int HISTORY_CHARGE_RULE_EDIT = 55;

	int HISTORY_PAY_RULES_LIST = 56;
	int HISTORY_PAY_RULE_EDIT = 57;

	int HISTORY_STATE_WEARENDA_EDIT = 58;

	int US_PAYMENTS_LIST = 59;
	int US_PAYMENT_EDIT = 60;

	int US_CHARGES_LIST = 61;
	int US_CHARGE_EDIT = 62;

	int CHANNEL_PAYMENTS_LIST = 63;
	int CHANNEL_PAYMENT_EDIT = 64;

	int CHANNEL_CHARGES_LIST = 65;
	int CHANNEL_CHARGE_EDIT = 66;

	int START_PROLONGATIONS_LIST = 67;
	int START_PROLONGATION_FORM = 68;
	int EXEC_PROLONGATION_FORM = 69;
	int JOURNAL_PROLONGATIONS_LIST = 70;

	int START_CHARGES_LIST = 71;
	int START_CHARGE_FORM = 72;
	int EXEC_CHARGE_FORM = 73;
	int JOURNAL_CHARGES_LIST = 74;

	int START_PAYMENTS_LIST = 75;
	int START_PAYMENT_FORM = 76;
	int EXEC_PAYMENT_FORM = 77;
	int JOURNAL_PAYMENTS_LIST = 78;

	int OPERATOR_LOOKUP = 79;

	int POS_MULTI = 80;
	int HISTORY_POS_MULTI = 81;
	//int CONTRACT_MULTI		= 82;
	int AGREEMENT_INFO = 83;
	int NFS_LIST = 84;
	int NFS_PRINT = 85;
	int ARENDA_TO_NFS_ZP_LIST = 86;
	int NFS_ZP_LOOKUP_LIST = 87;
	int MEMO_LIST = 88;
	int MEMO_EDIT = 89;
	int MEMO_POS_LIST = 90;
	int MEMO_POS_EDIT = 91;
	int LEASE_RES_BIL_2NRI_LOOKUP_LIST = 92;

	int RENTER_LOOKUP = 93;

	int FROMCONTRACT_MUTUAL_REGLMNTS_LIST = 94;
	int FROMCONTRACT_MAINPARAMS_MUTREGLMNT_EDIT = 95;
	int FROMCONTRACT_PHONES_MUTREGLMNT_LIST = 96;
	int FROMCONTRACT_PHONE_MUTREGLMNT_EDIT = 97;
	int FROMCONTRACT_CONTRACTS_MUTREGLMNT_LIST = 98;
	int FROMCONTRACT_CONTRACT_MUTREGLMNT_EDIT = 99;
	int FROMCONTRACT_MUTUAL_RULES_LIST = 100;
	int FROMCONTRACT_MUTUAL_RULE_EDIT = 101;
	int FROMCONTRACT_MUTACTS_LIST = 102;
	int FROMCONTRACT_MUTACT_EDIT = 103;

	int FROMHISTORY_MUTUAL_REGLMNTS_LIST = 104;
	int FROMHISTORY_MAINPARAMS_MUTREGLMNT_EDIT = 105;
	int FROMHISTORY_PHONES_MUTREGLMNT_LIST = 106;
	int FROMHISTORY_PHONE_MUTREGLMNT_EDIT = 107;
	int FROMHISTORY_CONTRACTS_MUTREGLMNT_LIST = 108;
	int FROMHISTORY_CONTRACT_MUTREGLMNT_EDIT = 109;
	int FROMHISTORY_MUTUAL_RULES_LIST = 110;
	int FROMHISTORY_MUTUAL_RULE_EDIT = 111;
	int FROMHISTORY_MUTACTS_LIST = 112;
	int FROMHISTORY_MUTACT_EDIT = 113;

	int STATE_MUTREGLMNT_EDIT = 114;
	int FROMCONTRACT_STATE_MUTREGLMNT_EDIT = 115;
	int FROMHISTORY_STATE_MUTREGLMNT_EDIT = 116;

	int COPY_REGLAMENT = 117;
	int FROMCONTRACT_COPY_REGLAMENT = 118;
	int FROMHISTORY_COPY_REGLAMENT = 119;

	int STATE_MUTACT_EDIT = 120;
	int FROMCONTRACT_STATE_MUTACT_EDIT = 121;
	int FROMHISTORY_STATE_MUTACT_EDIT = 122;

	int STATE_PAYMENT_EDIT = 123;
	int HISTORY_STATE_PAYMENT_EDIT = 124;
	int US_STATE_PAYMENT_EDIT = 125;
	int CHANNEL_STATE_PAYMENT_EDIT = 126;

	int REGLAMENT_CONTRACT_PRIORS_LIST = 127;
	int REGLAMENT_CONTRACT_PRIOR_EDIT = 128;
	int FROMCONTRACT_REGLAMENT_CONTRACT_PRIORS_LIST = 129;
	int FROMCONTRACT_REGLAMENT_CONTRACT_PRIOR_EDIT = 130;
	int FROMHISTORY_REGLAMENT_CONTRACT_PRIORS_LIST = 131;
	int FROMHISTORY_REGLAMENT_CONTRACT_PRIOR_EDIT = 132;

	int SALDO_LIST = 133;
	int SALDO_EDIT = 134;
	int HISTORY_SALDO_LIST = 135;
	int HISTORY_SALDO_EDIT = 136;
	int US_SALDO_LIST = 137;
	int US_SALDO_EDIT = 138;
	int CHANNEL_SALDO_LIST = 139;
	int CHANNEL_SALDO_EDIT = 140;

	int CALC_CONTRACT_STEP1 = 141;
	int CALC_CONTRACT_STEP2 = 142;
	int CALC_CONTRACT_STEP3 = 143;

	int PAYMENT_RATES_LIST = 144;
	int PAYMENT_RATE_EDIT = 145;
	int HISTORY_PAYMENT_RATES_LIST = 146;
	int HISTORY_PAYMENT_RATE_EDIT = 147;
	int US_PAYMENT_RATES_LIST = 148;
	int US_PAYMENT_RATE_EDIT = 149;
	int CHANNEL_PAYMENT_RATES_LIST = 150;
	int CHANNEL_PAYMENT_RATE_EDIT = 151;

	int START_ACT_LIST = 152;
	int JOURNAL_ACT_LIST = 153;
	int FROMCONTRACT_START_ACT_LIST = 154;
	int FROMCONTRACT_JOURNAL_ACT_LIST = 155;
	int FROMHISTORY_START_ACT_LIST = 156;
	int FROMHISTORY_JOURNAL_ACT_LIST = 157;

	int CHARGE_RATES_LIST = 158;
	int CHARGE_RATE_EDIT = 159;
	int HISTORY_CHARGE_RATES_LIST = 160;
	int HISTORY_CHARGE_RATE_EDIT = 161;
	int US_CHARGE_RATES_LIST = 162;
	int US_CHARGE_RATE_EDIT = 163;
	int CHANNEL_CHARGE_RATES_LIST = 164;
	int CHANNEL_CHARGE_RATE_EDIT = 165;

	int HISTORY_CALC_CONTRACT_STEP1 = 166;
	int HISTORY_CALC_CONTRACT_STEP2 = 167;
	int HISTORY_CALC_CONTRACT_STEP3 = 168;

	int PAYMENT_LOOKUP = 169;

	int CHARGE_DNOP_LIST = 170;
	int CHARGE_DNOP_EDIT = 171;
	int HISTORY_CHARGE_DNOP_LIST = 172;
	int HISTORY_CHARGE_DNOP_EDIT = 173;
	int US_CHARGE_DNOP_LIST = 174;
	int US_CHARGE_DNOP_EDIT = 175;
	int CHANNEL_CHARGE_DNOP_LIST = 176;
	int CHANNEL_CHARGE_DNOP_EDIT = 177;

	int MUTACTS_EQUAL_REPORT = 178;
	int MUTACTS_CALC_REPORT = 179;

	int BANKLOOKUP = 180;

	int FACTURA_EDIT = 181;
	int HISTORY_FACTURA_EDIT = 182;
	int PRINT_FACTURA = 183;
	int HISTORY_PRINT_FACTURA = 184;

	int FACTURA_MUTACT_LIST = 185;
	int FACTURA_MUTACT_EDIT = 186;
	int FACTURA_POS_MUTACT_LIST = 187;
	int FACTURA_POS_MUTACT_EDIT = 188;
	int FROMCONTRACT_FACTURA_MUTACT_LIST = 189;
	int FROMCONTRACT_FACTURA_MUTACT_EDIT = 190;
	int FROMCONTRACT_FACTURA_POS_MUTACT_LIST = 191;
	int FROMCONTRACT_FACTURA_POS_MUTACT_EDIT = 192;
	int FROMHISTORY_FACTURA_MUTACT_LIST = 193;
	int FROMHISTORY_FACTURA_MUTACT_EDIT = 194;
	int FROMHISTORY_FACTURA_POS_MUTACT_LIST = 195;
	int FROMHISTORY_FACTURA_POS_MUTACT_EDIT = 196;

	int CALC_HISTORY = 197;
	int ERROR_CALC_HISTORY = 198;

	int PLATINUM_DOGOVOR_FORM = 200;
	int PLATINUM_ERROR_MOVECONTRACTTOPIE = 201;
	int PLATINUM_ERROR_HISTORY_MOVECONTRACTTOPIE = 202;
	int PLATINUM_ERROR_MOVEPAYTOPIE = 203;
	int PLATINUM_ERROR_HISTORY_MOVEPAYTOPIE = 204;
	int PLATINUM_GETPAYFROMPLATINUM = 205;
	int PLATINUM_HISTORY_GETPAYFROMPLATINUM = 206;

	int GETPAYS_BYCONTRACT = 207;
	int HISTORY_GETPAYS_BYCONTRACT = 208;

	int DOG_HISTORY_LIST = 209;
	int DOG_HIST_CHRG_LIST = 210; 
	int DOG_HIST_PAY_LIST = 211;
	int DOG_ABONENTS_LIST = 212;
	int ACT_PARAMS_PRINT = 213;
	int ACT_CONTENTS_LIST = 214;
	int MUTACT_WORD = 215;
	int RESP_PAYS_LIST = 216;
	int TARIF_PLAN_LOOKUP_LIST = 217;
	int BILLING_SERVISES_LOOKUP_LIST = 218;
	int COMPLET_WORK_ACTS_LIST = 219;
	int COMPLET_WORK_AKT_EDIT = 220;
	int CWA_CHARGES__PRINT = 221;
	int NFS_LIST_DETACH = 222;
	int LIST_FROM_POSITION = 223;
	int COURIER_DELIVERY_LIST= 224;
	int MEMO_LIST_DETACH = 225;
	int MEMO_DETACH_FORM = 226;
	int CHARGE_RULE_DIALOG_EDIT = 227;
	int PAY_RULE_DIALOG_EDIT = 228;
	int LIST_LICENCE = 229;
	int RATE_LIST = 230;
	int LAWYERS_NOTE_DIALOG = 231;
	int FLAGS_FROM_LEASE_CHARGES_DIALOG=232;
	int LICENCE_DIALOG = 233;
	int CONTRACT_COMMENT_DIALOG = 234;
	int LOAN_CONTRACT_LIST = 235;
	int LOAN_CONTRACT_DIALOG = 236;
	int LOAN_CONTRACT_STATE = 237;
	int LOAN_CONTRACT_MEMO_LIST = 238;
	int LOAN_CONTRACT_MEMO = 239;
	int LOAN_AKT_GET_PUT_LIST = 240;
	int LOAN_AKT_GET_PUT_DIALOG = 241;
	
	int SCHET_FACT_LIST = 242;
	int SCHET_FACT_DIALOG = 243;
	
	int REGISTRY_BUCH_DOCS_LIST = 244;
	int REGISTRY_BUCH_DOCS_DIALOG = 245;
	int REGISTRY_BUCH_DOCS_COMPOSITION_SF = 246;
	int REGISTRY_BUCH_DOCS_COMPOSITION_CWA = 247;
	int REGISTRY_BUCH_DOCS_COMPOSITION_LeaseDoc = 248;
	
	int PRIORITY_CONTRACT_FOR_ACT_LIST = 249;
	
	int SCHET_FACT_FOR_CHARGE_LIST = 250;
	
	
	int LEASE_PAY_OFFICE_MEMO_LIST = 251;
	int LEASE_PAY_OFFICE_MEMO_DIALOG = 252;
	
	int PAY_RULE_LOOKUP_LIST = 253;
	
	int LEASE_ZP_OFFICE_MEMO_LIST = 254;
	int LEASE_ZP_OFFICE_MEMO_DIALOG = 255;
	
	int HISTORY_LOOKUP_LIST = 256;
	
	int ARENDA_TO_NFS_ZP_LOOKUP_LIST = 257;
	
	int LEASE_CONTRACT_PROBLEM_LIST = 258;
	int LEASE_CONTRACT_PROBLEM_DIALOG = 259;
	int LEASE_PROBLEM_LIST = 260;
	int POSITIONS_DIALOG_LIST = 261;
	
	int COMPLET_WORK_ACTS_FOR_CHARGE_LIST = 262;
	int COMPLET_WORK_AKT_DIALOG = 263;
	int CHARGE_LIST_LINK_TO_COMPLET_WORK_AKT = 264;
	
	int REGISTRY_BUCH_DOCS_COMPOSITION_SF_CWA = 265;
	
	int DNOP_FOR_CHARGES_LIST = 266;
	int DNOP_DIALOG = 267;
	
	int REGISTRY_BUCH_DOCS_LIST_FOR_RETURN_DOCUMENT_GROUP = 268;
	int REGISTRY_BUCH_DOCS_LIST_FOR_INITIAL_GROUP = 269;
	
	int REGISTRY_BUCH_DOCS_COMPOSITION_SF_IG = 270;
	int REGISTRY_BUCH_DOCS_COMPOSITION_CWA_IG = 271;
	int REGISTRY_BUCH_DOCS_COMPOSITION_LeaseDoc_IG = 272;
	int REGISTRY_BUCH_DOCS_COMPOSITION_SF_CWA_IG = 273;
	
	int REGISTRY_BUCH_DOCS_COMPOSITION_SF_RG = 274;
	int REGISTRY_BUCH_DOCS_COMPOSITION_CWA_RG = 275;
	int REGISTRY_BUCH_DOCS_COMPOSITION_LeaseDoc_RG = 276;
	int REGISTRY_BUCH_DOCS_COMPOSITION_SF_CWA_RG = 277;
	
	int SALDO_DETAIL_LIST = 278;
	int SALDO_DETAIL_DIALOG = 279;
	
	int ABONENT_SALDO_DETAIL_LIST = 280;
	int ABONENT_SALDO_DETAIL_DIALOG = 281;
	int ABONENT_INFO = 282;
	
	int REGISTRY_BUCH_DOCS_HISTORY = 283;
	
	int DNOP_FOR_PAYMENTS_LIST = 284;
	
	int CHARGE_LIST_LINK_TO_PAYMENT = 285;
	
	int REGISTRY_BUCH_DOCS_COMPOSITION_MUTUAL_ACT_IG = 286;
	int REGISTRY_BUCH_DOCS_COMPOSITION_MUTUAL_ACT_RG = 287;
	int REGISTRY_BUCH_DOCS_COMPOSITION_MUTUAL_ACT = 288;	

	int GET_SPR_ARENDA = 400;
	int GET_SPR_ARENDA_RESULT = 401;
	int GET_BANKS = 402;
	int GET_BANKS_RESULT = 403;
	int GET_PAYS = 404;
	int GET_PAYS_RESULT = 405;
	int BANKLIST = 406;

	// Abonent Contracts
	int BENS_LIST = 500;
	int BEN_EDIT = 501;
	int ABONENTBAN_EDIT = 502;
	int ABONENTS_LIST = 503;
	int ABONENT_EDIT = 504;
	int ABONENT_STATE = 505;
	int ABONENT_BILLS_LIST = 506;
	int ABONENT_BILL_EDIT = 507;
	int ABONENT_BILL_POSES_LIST = 508;
	int ABONENT_BILL_POS_EDIT = 509;
	int ABONENT_PAYMENTS_LIST = 510;
	int ABONENT_CHARGES_LIST = 511;
	int ABONENT_BILL_FUNC = 512;
	int ABONENT_CHARGE_DNOP_LIST = 513;
	int ABONENT_CHARGE_DNOP_EDIT = 514;
	int ABONENT_PAYS_LIST = 515;
	int ABONENT_PAYED_LIST = 516;
	int ABONENT_PAY_EDIT = 517;
	//int ABONENT_BILL_MOVE							= 518;
	//int ABONENT_CHARGE_RULES_LIST					= 519;
	int ABONENT_CHARGE_RATES_LIST = 520;
	int ABONENT_CHARGE_RATE_EDIT = 521;
	int ABONENT_PAYMENT_EDIT = 522;
	int ABONENT_PAYMENT_RATES_LIST = 523;
	int ABONENT_PAYMENT_RATE_EDIT = 524;

	int ABONENT_STATE_PAYMENT_EDIT = 525;
	//int ABONENT_PAY_RULE_EDIT						= 526;
	int ABONENT_CHARGE_EDIT = 527;
	int ABONENT_BILLED_LIST = 528;
	int ABONENT_SALDO_LIST = 529;
	int ABONENT_SALDO_EDIT = 530;
	int ABONENT_BILL_QUERY = 531;
	int ABONENT_BILL_QUERY_TO_RESULT = 532;
	int ABONENT_BILL_QUERY_FROM_RESULT = 533;
	int ABONENT_BILL_START_LIST = 534;
	int ABONENT_BILL_JOURNAL_LIST = 535;
	int ABONENT_BILL_HANDLE_INNRI = 536;
	int ABONENT_PAY_HANDLE_INNRI = 537;
	int ABONENT_FROMBILLHANDLEINNRI_BILL_JOURNAL_LIST = 538;
	int ABONENT_FROMPAYHANDLEINNRI_BILL_JOURNAL_LIST = 539;
	int ABONENT_BILL_LINKS_LIST = 540;
	int ABONENT_BILL_LINK_EDIT = 541;
	int ABONENT_BILL_LOOKUP_LIST = 542;
	int CHARGE_LIST = 543;
	int CHARGE_DIALOG = 544;
	int CHARGE_AUTOMATIC_DIALOG_FORM = 545;
	int CHARGE_LIST_LINK_TO_SCHET_FACT = 546;

	// Reports
	int ARENDA_REPORT1_PARAMS = 600;
	int ARENDA_REPORT1 = 601;
	int ARENDA_REPORT2_PARAMS = 602;
	int ARENDA_REPORT2 = 603;
	int ARENDA_REPORT3_PARAMS = 604;
	int ARENDA_REPORT3 = 605;
	int ARENDA_REPORT4_PARAMS = 606;
	int ARENDA_REPORT4 = 607;
	int ARENDA_REPORT5_PARAMS = 608;
	int ARENDA_REPORT5 = 609;
	int ARENDA_REPORT6_PARAMS = 610;
	int ARENDA_REPORT6 = 611;
	int ARENDA_REPORT7_PARAMS = 612;
	int ARENDA_REPORT7 = 613;
	int ARENDA_REPORT8_PARAMS = 614;
	int ARENDA_REPORT8 = 615;
	int ARENDA_REPORT9_PARAMS = 616;
	int ARENDA_REPORT9 = 617;
	int ARENDA_REPORT10_PARAMS = 618;
	int ARENDA_REPORT10 = 619;
	int ARENDA_REPORT11_PARAMS = 620;
	int ARENDA_REPORT11 = 621;
	int ARENDA_REPORT3XLS = 622;
	
	//Журнал:
	int JOURNAL_LIST = 700;
	
	//Utilities
	int CHOOSE_AVAILABLE_REGION = 800;
}
