package com.hps.july.arenda;

/**
 * Констатны ошибок модуля-приложения "Аренда"
 * Creation date: (15.01.2003 17:21:33)
 * @author: Sergey Gourov
 */
public interface Errors {
	int JOURNAL_STRMESSAGE							= 0;
	
	int JOURNAL_PROLONGATION_SUCCESS				= 1;
	int JOURNAL_PROLONGATION_ERROR_ACTIVE			= 2;
	int JOURNAL_PROLONGATION_ERROR_STATE			= 3;
	int JOURNAL_PROLONGATION_ERROR_EXTENDTYPE		= 4;
	int JOURNAL_PROLONGATION_ERROR_EXTENDPERIOD		= 5;
	int JOURNAL_PROLONGATION_ERROR_GENERAL			= 6;
	
	int JOURNAL_PROLONGATION_WARNING_CONTRACTSNOTEXIST	= 7;
	
	
	int JOURNAL_CHARGES_SUCCESS						= 20;
	int JOURNAL_CHARGES_WARNING_NOTCHANGE			= 21;
	int JOURNAL_CHARGES_ERROR_RELATION				= 22;
	int JOURNAL_CHARGES_ERROR_PERIOD				= 23;
	int JOURNAL_CHARGES_ERROR_GENERAL				= 24;
	
	int JOURNAL_CHARGES_WARNING_CONTRACTSNOTEXIST	= 25;
	int JOURNAL_CHARGES_WARNING_SALDONOTEXIST		= 26;
	int JOURNAL_CHARGES_WARNING_CLOSEPERIOD			= 27;
	int JOURNAL_CHARGES_WARNING_HANDCHARGE			= 28;
	int JOURNAL_CHARGES_WARNING_HASDNOP				= 29;
	int JOURNAL_CHARGES_ERROR_DATERULE				= 30;
	int JOURNAL_CHARGES_ERROR_NDS					= 31;
	
	int JOURNAL_PAYMENTS_SUCCESS					= 60;
	int JOURNAL_PAYMENTS_ERROR_PERIOD				= 61;
	int JOURNAL_PAYMENTS_WARNING_NOTCHANGE			= 62;
	int JOURNAL_PAYMENTS_ERROR_GENERAL				= 63;
	
	int JOURNAL_PAYMENTS_WARNING_CONTRACTSNOTEXIST	= 64;
	int JOURNAL_PAYMENTS_WARNING_SALDONOTEXIST		= 65;
	int JOURNAL_PAYMENTS_WARNING_DATESALDO			= 66;
	int JOURNAL_PAYMENTS_WARNING_NOTEDIT			= 67;
	int JOURNAL_PAYMENTS_ERROR_PPTYPE				= 68;
	int JOURNAL_PAYMENTS_WARNING_ADDDAYTOPAYDATE	= 69;
	int JOURNAL_PAYMENTS_ERROR_NDS					= 70;
	int JOURNAL_PAYMENTS_ERROR_RATE					= 71;
	
	int JOURNAL_CALCACT_ERROR_ROLLBACK				= 100;
	
	int JOURNAL_CALCACT_ERROR_REGINSERT				= 101;
	int JOURNAL_CALCACT_ERROR_REGCLOSE				= 102;
	int JOURNAL_CALCACT_ERROR_FINDSALDO				= 103;
	int JOURNAL_CALCACT_ERROR_RESOURCE				= 104;
	int JOURNAL_CALCACT_ERROR_RESOURCE2				= 105;
	int JOURNAL_CALCACT_ERROR_CHARGEDATE			= 106;
	int JOURNAL_CALCACT_ERROR_PAYDATE				= 107;
	
	int JOURNAL_CALCACT_ERROR_CALCRATE				= 108;
	int JOURNAL_CALCACT_ERROR_SYSTEMRES1			= 109;
	int JOURNAL_CALCACT_ERROR_SYSTEMRES2			= 110;
	int JOURNAL_CALCACT_ERROR_FINDRUR				= 111;
	int JOURNAL_CALCACT_ERROR_CHARGERATEDATE		= 112;
	int JOURNAL_CALCACT_ERROR_DEFINERATE			= 113;
	int JOURNAL_CALCACT_ERROR_NORATE				= 114;

	int JOURNAL_CALCACT_ERROR_CALCACT				= 116;
	int JOURNAL_CALCACT_ERROR_MUTUALCHARGES			= 117;
	int JOURNAL_CALCACT_ERROR_MUTUALCHARGES2		= 118;
	int JOURNAL_CALCACT_ERROR_MAKEBALANSINGCHARGE	= 119;
	int JOURNAL_CALCACT_ERROR_MAKEBALANSINGCHARGE2	= 120;
	int JOURNAL_CALCACT_ERROR_ADDSALDO				= 121;
	int JOURNAL_CALCACT_ERROR_NOTRATECHARGE			= 122;
	int JOURNAL_CALCACT_ERROR_CLOSECHARGE			= 123;
	int JOURNAL_CALCACT_ERROR_CLOSECHARGE2			= 124;
	int JOURNAL_CALCACT_ERROR_RATEPAY				= 127;
	int JOURNAL_CALCACT_ERROR_CONTRACTSUNIC			= 128;
}
