package com.hps.july.trailcom.beans;

import java.rmi.RemoteException;
import java.security.Identity;
import java.util.Properties;
import javax.ejb.*;
/**
 * This is an Entity Bean class with CMP fields
 * Данные TRAILCOM - радиорелейные пролеты
 */
public class RRLHops2Bean implements EntityBean {
	public Integer accumid_a;
	public Integer accumid_b;
	public java.math.BigDecimal azimuth;
	public java.math.BigDecimal cable_2mb_a;
	public java.math.BigDecimal cable_2mbr_b;
	public java.math.BigDecimal cable_power_a;
	public java.math.BigDecimal cable_power_b;
	public java.math.BigDecimal cable_rrl_a;
	public java.math.BigDecimal cable_rrl_b;
	public String comment_a;
	public String comment_b;
	public java.math.BigDecimal diam_a;
	public java.math.BigDecimal diam_b;
	private javax.ejb.EntityContext entityContext = null;
	public Integer file_number;
	public Integer file_shortnumber;
	public java.math.BigDecimal frequency_a1;
	public java.math.BigDecimal frequency_a2;
	public java.math.BigDecimal frequency_b1;
	public java.math.BigDecimal frequency_b2;
	public java.math.BigDecimal height_a;
	public java.math.BigDecimal height_b;
	public Integer number_in_file;
	public java.math.BigDecimal power_a;
	public java.math.BigDecimal power_b;
	private final static long serialVersionUID = 3206093459760846163L;
	public java.math.BigDecimal signal_calc_a;
	public java.math.BigDecimal signal_calc_b;
	public java.math.BigDecimal signal_real_a;
	public java.math.BigDecimal signal_real_b;
	public String type_hw;
	public java.lang.Integer hopid_hopsid;
	private transient com.ibm.ivj.ejb.associations.interfaces.SingleLink hopidLink = null;
	public java.math.BigDecimal frequency_a_doc;
	public java.math.BigDecimal frequency_b_doc;
	public java.math.BigDecimal diam_a_doc;
	public java.math.BigDecimal height_a_doc;
	public java.math.BigDecimal diam_b_doc;
	public java.math.BigDecimal height_b_doc;
	public Integer resource_doc;
	public java.math.BigDecimal power_doc;
	public String speed_doc;
	public java.math.BigDecimal azimuthAB_Doc;
	public java.math.BigDecimal azimuthBA_Doc;
	public String comment_doc;
	public java.math.BigDecimal diam2_a;
	public java.math.BigDecimal diam2_b;
	public Integer capacity;
	public String sfonumber;
/**
 * This method was generated by the VisualAge for Java EJB AccessBean tool.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public java.util.Hashtable _copyFromEJB() {
        com.ibm.ivj.ejb.runtime.AccessBeanHashtable h = new com.ibm.ivj.ejb.runtime.AccessBeanHashtable();

        h.put("cable_2mbr_b", getCable_2mbr_b());
        h.put("azimuth", getAzimuth());
        h.put("diam2_b", getDiam2_b());
        h.put("frequency_a2", getFrequency_a2());
        h.put("diam2_a", getDiam2_a());
        h.put("frequency_a1", getFrequency_a1());
        h.put("height_b", getHeight_b());
        h.put("height_a", getHeight_a());
        h.put("file_number", getFile_number());
        h.put("diam_b_doc", getDiam_b_doc());
        h.put("accumid_b", getAccumid_b());
        h.put("accumid_a", getAccumid_a());
        h.put("azimuthBA_Doc", getAzimuthBA_Doc());
        h.put("speed_doc", getSpeed_doc());
        h.put("power_doc", getPower_doc());
        h.put("signal_calc_b", getSignal_calc_b());
        h.put("signal_calc_a", getSignal_calc_a());
        h.put("cable_2mb_a", getCable_2mb_a());
        h.put("comment_b", getComment_b());
        h.put("number_in_file", getNumber_in_file());
        h.put("comment_a", getComment_a());
        h.put("signal_real_b", getSignal_real_b());
        h.put("signal_real_a", getSignal_real_a());
        h.put("azimuthAB_Doc", getAzimuthAB_Doc());
        h.put("comment_doc", getComment_doc());
        h.put("file_shortnumber", getFile_shortnumber());
        h.put("cable_power_b", getCable_power_b());
        h.put("cable_power_a", getCable_power_a());
        h.put("height_a_doc", getHeight_a_doc());
        h.put("hopidKey", getHopidKey());
        h.put("frequency_a_doc", getFrequency_a_doc());
        h.put("resource_doc", getResource_doc());
        h.put("frequency_b2", getFrequency_b2());
        h.put("frequency_b1", getFrequency_b1());
        h.put("height_b_doc", getHeight_b_doc());
        h.put("diam_b", getDiam_b());
        h.put("diam_a", getDiam_a());
        h.put("type_hw", getType_hw());
        h.put("frequency_b_doc", getFrequency_b_doc());
        h.put("capacity", getCapacity());
        h.put("power_b", getPower_b());
        h.put("cable_rrl_b", getCable_rrl_b());
        h.put("cable_rrl_a", getCable_rrl_a());
        h.put("sfonumber", getSfonumber());
        h.put("power_a", getPower_a());
        h.put("diam_a_doc", getDiam_a_doc());
        h.put("__Key", getEntityContext().getPrimaryKey());

        return h;

}
/**
 * This method was generated by the VisualAge for Java EJB AccessBean tool.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void _copyToEJB(java.util.Hashtable h) {
        java.math.BigDecimal localCable_2mbr_b = (java.math.BigDecimal) h.get("cable_2mbr_b");
        java.math.BigDecimal localAzimuth = (java.math.BigDecimal) h.get("azimuth");
        java.math.BigDecimal localDiam2_b = (java.math.BigDecimal) h.get("diam2_b");
        java.math.BigDecimal localFrequency_a2 = (java.math.BigDecimal) h.get("frequency_a2");
        java.math.BigDecimal localDiam2_a = (java.math.BigDecimal) h.get("diam2_a");
        java.math.BigDecimal localFrequency_a1 = (java.math.BigDecimal) h.get("frequency_a1");
        java.math.BigDecimal localHeight_b = (java.math.BigDecimal) h.get("height_b");
        java.math.BigDecimal localHeight_a = (java.math.BigDecimal) h.get("height_a");
        java.lang.Integer localFile_number = (java.lang.Integer) h.get("file_number");
        java.math.BigDecimal localDiam_b_doc = (java.math.BigDecimal) h.get("diam_b_doc");
        java.lang.Integer localAccumid_b = (java.lang.Integer) h.get("accumid_b");
        java.lang.Integer localAccumid_a = (java.lang.Integer) h.get("accumid_a");
        java.math.BigDecimal localAzimuthBA_Doc = (java.math.BigDecimal) h.get("azimuthBA_Doc");
        java.lang.String localSpeed_doc = (java.lang.String) h.get("speed_doc");
        java.math.BigDecimal localPower_doc = (java.math.BigDecimal) h.get("power_doc");
        java.math.BigDecimal localSignal_calc_b = (java.math.BigDecimal) h.get("signal_calc_b");
        java.math.BigDecimal localSignal_calc_a = (java.math.BigDecimal) h.get("signal_calc_a");
        java.math.BigDecimal localCable_2mb_a = (java.math.BigDecimal) h.get("cable_2mb_a");
        java.lang.String localComment_b = (java.lang.String) h.get("comment_b");
        java.lang.Integer localNumber_in_file = (java.lang.Integer) h.get("number_in_file");
        java.lang.String localComment_a = (java.lang.String) h.get("comment_a");
        java.math.BigDecimal localSignal_real_b = (java.math.BigDecimal) h.get("signal_real_b");
        java.math.BigDecimal localSignal_real_a = (java.math.BigDecimal) h.get("signal_real_a");
        java.math.BigDecimal localAzimuthAB_Doc = (java.math.BigDecimal) h.get("azimuthAB_Doc");
        java.lang.String localComment_doc = (java.lang.String) h.get("comment_doc");
        java.lang.Integer localFile_shortnumber = (java.lang.Integer) h.get("file_shortnumber");
        java.math.BigDecimal localCable_power_b = (java.math.BigDecimal) h.get("cable_power_b");
        java.math.BigDecimal localCable_power_a = (java.math.BigDecimal) h.get("cable_power_a");
        java.math.BigDecimal localHeight_a_doc = (java.math.BigDecimal) h.get("height_a_doc");
        java.math.BigDecimal localFrequency_a_doc = (java.math.BigDecimal) h.get("frequency_a_doc");
        java.lang.Integer localResource_doc = (java.lang.Integer) h.get("resource_doc");
        java.math.BigDecimal localFrequency_b2 = (java.math.BigDecimal) h.get("frequency_b2");
        java.math.BigDecimal localFrequency_b1 = (java.math.BigDecimal) h.get("frequency_b1");
        java.math.BigDecimal localHeight_b_doc = (java.math.BigDecimal) h.get("height_b_doc");
        java.math.BigDecimal localDiam_b = (java.math.BigDecimal) h.get("diam_b");
        java.math.BigDecimal localDiam_a = (java.math.BigDecimal) h.get("diam_a");
        java.lang.String localType_hw = (java.lang.String) h.get("type_hw");
        java.math.BigDecimal localFrequency_b_doc = (java.math.BigDecimal) h.get("frequency_b_doc");
        java.lang.Integer localCapacity = (java.lang.Integer) h.get("capacity");
        java.math.BigDecimal localPower_b = (java.math.BigDecimal) h.get("power_b");
        java.math.BigDecimal localCable_rrl_b = (java.math.BigDecimal) h.get("cable_rrl_b");
        java.math.BigDecimal localCable_rrl_a = (java.math.BigDecimal) h.get("cable_rrl_a");
        java.lang.String localSfonumber = (java.lang.String) h.get("sfonumber");
        java.math.BigDecimal localPower_a = (java.math.BigDecimal) h.get("power_a");
        java.math.BigDecimal localDiam_a_doc = (java.math.BigDecimal) h.get("diam_a_doc");

        if ( h.containsKey("cable_2mbr_b") )
            setCable_2mbr_b((localCable_2mbr_b));
        if ( h.containsKey("azimuth") )
            setAzimuth((localAzimuth));
        if ( h.containsKey("diam2_b") )
            setDiam2_b((localDiam2_b));
        if ( h.containsKey("frequency_a2") )
            setFrequency_a2((localFrequency_a2));
        if ( h.containsKey("diam2_a") )
            setDiam2_a((localDiam2_a));
        if ( h.containsKey("frequency_a1") )
            setFrequency_a1((localFrequency_a1));
        if ( h.containsKey("height_b") )
            setHeight_b((localHeight_b));
        if ( h.containsKey("height_a") )
            setHeight_a((localHeight_a));
        if ( h.containsKey("file_number") )
            setFile_number((localFile_number));
        if ( h.containsKey("diam_b_doc") )
            setDiam_b_doc((localDiam_b_doc));
        if ( h.containsKey("accumid_b") )
            setAccumid_b((localAccumid_b));
        if ( h.containsKey("accumid_a") )
            setAccumid_a((localAccumid_a));
        if ( h.containsKey("azimuthBA_Doc") )
            setAzimuthBA_Doc((localAzimuthBA_Doc));
        if ( h.containsKey("speed_doc") )
            setSpeed_doc((localSpeed_doc));
        if ( h.containsKey("power_doc") )
            setPower_doc((localPower_doc));
        if ( h.containsKey("signal_calc_b") )
            setSignal_calc_b((localSignal_calc_b));
        if ( h.containsKey("signal_calc_a") )
            setSignal_calc_a((localSignal_calc_a));
        if ( h.containsKey("cable_2mb_a") )
            setCable_2mb_a((localCable_2mb_a));
        if ( h.containsKey("comment_b") )
            setComment_b((localComment_b));
        if ( h.containsKey("number_in_file") )
            setNumber_in_file((localNumber_in_file));
        if ( h.containsKey("comment_a") )
            setComment_a((localComment_a));
        if ( h.containsKey("signal_real_b") )
            setSignal_real_b((localSignal_real_b));
        if ( h.containsKey("signal_real_a") )
            setSignal_real_a((localSignal_real_a));
        if ( h.containsKey("azimuthAB_Doc") )
            setAzimuthAB_Doc((localAzimuthAB_Doc));
        if ( h.containsKey("comment_doc") )
            setComment_doc((localComment_doc));
        if ( h.containsKey("file_shortnumber") )
            setFile_shortnumber((localFile_shortnumber));
        if ( h.containsKey("cable_power_b") )
            setCable_power_b((localCable_power_b));
        if ( h.containsKey("cable_power_a") )
            setCable_power_a((localCable_power_a));
        if ( h.containsKey("height_a_doc") )
            setHeight_a_doc((localHeight_a_doc));
        if ( h.containsKey("frequency_a_doc") )
            setFrequency_a_doc((localFrequency_a_doc));
        if ( h.containsKey("resource_doc") )
            setResource_doc((localResource_doc));
        if ( h.containsKey("frequency_b2") )
            setFrequency_b2((localFrequency_b2));
        if ( h.containsKey("frequency_b1") )
            setFrequency_b1((localFrequency_b1));
        if ( h.containsKey("height_b_doc") )
            setHeight_b_doc((localHeight_b_doc));
        if ( h.containsKey("diam_b") )
            setDiam_b((localDiam_b));
        if ( h.containsKey("diam_a") )
            setDiam_a((localDiam_a));
        if ( h.containsKey("type_hw") )
            setType_hw((localType_hw));
        if ( h.containsKey("frequency_b_doc") )
            setFrequency_b_doc((localFrequency_b_doc));
        if ( h.containsKey("capacity") )
            setCapacity((localCapacity));
        if ( h.containsKey("power_b") )
            setPower_b((localPower_b));
        if ( h.containsKey("cable_rrl_b") )
            setCable_rrl_b((localCable_rrl_b));
        if ( h.containsKey("cable_rrl_a") )
            setCable_rrl_a((localCable_rrl_a));
        if ( h.containsKey("sfonumber") )
            setSfonumber((localSfonumber));
        if ( h.containsKey("power_a") )
            setPower_a((localPower_a));
        if ( h.containsKey("diam_a_doc") )
            setDiam_a_doc((localDiam_a_doc));

}
/**
 * This method was generated for supporting the associations.
 * @return java.util.Vector
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected java.util.Vector _getLinks() {
	java.util.Vector links = new java.util.Vector();
	links.addElement(getHopidLink());
	return links;
}
/**
 * This method was generated for supporting the associations.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected void _initLinks() {
	hopidLink = null;
}
/**
 * This method was generated for supporting the associations.
 * @exception java.rmi.RemoteException The exception description.
 * @exception javax.ejb.RemoveException The exception description.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected void _removeLinks() throws java.rmi.RemoteException, javax.ejb.RemoveException {
	java.util.Enumeration links = _getLinks().elements();
	while (links.hasMoreElements()) {
		try {
			((com.ibm.ivj.ejb.associations.interfaces.Link) (links.nextElement())).remove();
		}
		catch (javax.ejb.FinderException e) {} //Consume Finder error since I am going away
	}
}
/**
 * ejbActivate method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbActivate() throws java.rmi.RemoteException {
	_initLinks();
}
/**
 * ejbCreate method for a CMP entity bean
 * @exception javax.ejb.CreateException The exception description.
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbCreate(int hopid) throws javax.ejb.CreateException, java.rmi.RemoteException {
	_initLinks();

	hopid_hopsid = new Integer(hopid);
	accumid_a = null;
	accumid_b = null;
	azimuth = null;
	cable_2mb_a = null;
	cable_2mbr_b = null;
	cable_power_a = null;
	cable_power_b = null;
	cable_rrl_a = null;
	cable_rrl_b = null;
	comment_a = null;
	comment_b = null;
	diam_a = null;
	diam_b = null;
	file_number = null;
	file_shortnumber = null;
	frequency_a1 = null;
	frequency_a2 = null;
	frequency_b1 = null;
	frequency_b2 = null;
	height_a = null;
	height_b = null;
	number_in_file = null;
	power_a = null;
	power_b = null;
	signal_calc_a = null;
	signal_calc_b = null;
	signal_real_a = null;
	signal_real_b = null;
	type_hw = null;
	frequency_a_doc = null;
	frequency_b_doc = null;
	diam_a_doc = null;
	height_a_doc = null;
	diam_b_doc = null;
	height_b_doc = null;
	resource_doc = null;
	power_doc = null;
	speed_doc = null;
	azimuthAB_Doc = null;
	azimuthBA_Doc = null;
	comment_doc = null;
	diam2_a = null;
	diam2_b = null;
	capacity = null;
	sfonumber = null;
}
/**
 * ejbLoad method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbLoad() throws java.rmi.RemoteException {
	_initLinks();
}
/**
 * ejbPassivate method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbPassivate() throws java.rmi.RemoteException {}
/**
 * ejbPostCreate method for a CMP entity bean
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbPostCreate() throws java.rmi.RemoteException {}
/**
 * ejbRemove method comment
 * @exception java.rmi.RemoteException The exception description.
 * @exception javax.ejb.RemoveException The exception description.
 */
public void ejbRemove() throws java.rmi.RemoteException, javax.ejb.RemoveException {
	_removeLinks();
}
/**
 * ejbStore method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void ejbStore() throws java.rmi.RemoteException {}
/**
 * Getter method for accumid_a
 * @return java.lang.Integer
 */
public java.lang.Integer getAccumid_a() {
	return accumid_a;
}
/**
 * Getter method for accumid_b
 * @return java.lang.Integer
 */
public java.lang.Integer getAccumid_b() {
	return accumid_b;
}
/**
 * Getter method for azimuth
 * @return java.lang.Double
 */
public java.math.BigDecimal getAzimuth() {
	return azimuth;
}
/**
 * Getter method for azimuthAB_Doc
 */
public java.math.BigDecimal getAzimuthAB_Doc() {
	return azimuthAB_Doc;
}
/**
 * Getter method for azimuthBA_Doc
 */
public java.math.BigDecimal getAzimuthBA_Doc() {
	return azimuthBA_Doc;
}
/**
 * Getter method for cable_2mb_a
 * @return java.lang.Double
 */
public java.math.BigDecimal getCable_2mb_a() {
	return cable_2mb_a;
}
/**
 * Getter method for cable_2mbr_b
 * @return java.lang.Double
 */
public java.math.BigDecimal getCable_2mbr_b() {
	return cable_2mbr_b;
}
/**
 * Getter method for cable_power_a
 * @return java.lang.Double
 */
public java.math.BigDecimal getCable_power_a() {
	return cable_power_a;
}
/**
 * Getter method for cable_power_b
 * @return java.lang.Double
 */
public java.math.BigDecimal getCable_power_b() {
	return cable_power_b;
}
/**
 * Getter method for cable_rrl_a
 * @return java.lang.Double
 */
public java.math.BigDecimal getCable_rrl_a() {
	return cable_rrl_a;
}
/**
 * Getter method for cable_rrl_b
 * @return java.lang.Double
 */
public java.math.BigDecimal getCable_rrl_b() {
	return cable_rrl_b;
}
/**
 * Getter method for capacity
 */
public java.lang.Integer getCapacity() {
	return capacity;
}
/**
 * Getter method for comment_a
 * @return java.lang.String
 */
public java.lang.String getComment_a() {
	return comment_a;
}
/**
 * Getter method for comment_b
 * @return java.lang.String
 */
public java.lang.String getComment_b() {
	return comment_b;
}
/**
 * Getter method for comment_doc
 */
public java.lang.String getComment_doc() {
	return comment_doc;
}
/**
 * Getter method for diam_a
 * @return java.lang.Double
 */
public java.math.BigDecimal getDiam_a() {
	return diam_a;
}
/**
 * Getter method for diam_a_doc
 */
public java.math.BigDecimal getDiam_a_doc() {
	return diam_a_doc;
}
/**
 * Getter method for diam_b
 * @return java.lang.Double
 */
public java.math.BigDecimal getDiam_b() {
	return diam_b;
}
/**
 * Getter method for diam_b_doc
 */
public java.math.BigDecimal getDiam_b_doc() {
	return diam_b_doc;
}
/**
 * Getter method for diam2_a
 */
public java.math.BigDecimal getDiam2_a() {
	return diam2_a;
}
/**
 * Getter method for diam2_b
 */
public java.math.BigDecimal getDiam2_b() {
	return diam2_b;
}
/**
 * getEntityContext method comment
 * @return javax.ejb.EntityContext
 */
public javax.ejb.EntityContext getEntityContext() {
	return entityContext;
}
/**
 * Getter method for file_number
 * @return java.lang.Integer
 */
public java.lang.Integer getFile_number() {
	return file_number;
}
/**
 * Getter method for file_shortnumber
 * @return java.lang.Integer
 */
public java.lang.Integer getFile_shortnumber() {
	return file_shortnumber;
}
/**
 * Getter method for frequency_a_doc
 */
public java.math.BigDecimal getFrequency_a_doc() {
	return frequency_a_doc;
}
/**
 * Getter method for frequency_a1
 * @return java.lang.Double
 */
public java.math.BigDecimal getFrequency_a1() {
	return frequency_a1;
}
/**
 * Getter method for frequency_a2
 * @return java.lang.Double
 */
public java.math.BigDecimal getFrequency_a2() {
	return frequency_a2;
}
/**
 * Getter method for frequency_b_doc
 */
public java.math.BigDecimal getFrequency_b_doc() {
	return frequency_b_doc;
}
/**
 * Getter method for frequency_b1
 * @return java.lang.Double
 */
public java.math.BigDecimal getFrequency_b1() {
	return frequency_b1;
}
/**
 * Getter method for frequency_b2
 * @return java.lang.Double
 */
public java.math.BigDecimal getFrequency_b2() {
	return frequency_b2;
}
/**
 * Getter method for height_a
 * @return java.lang.Double
 */
public java.math.BigDecimal getHeight_a() {
	return height_a;
}
/**
 * Getter method for height_a_doc
 */
public java.math.BigDecimal getHeight_a_doc() {
	return height_a_doc;
}
/**
 * Getter method for height_b
 * @return java.lang.Double
 */
public java.math.BigDecimal getHeight_b() {
	return height_b;
}
/**
 * Getter method for height_b_doc
 */
public java.math.BigDecimal getHeight_b_doc() {
	return height_b_doc;
}
/**
 * This method was generated for supporting the association named RRLHops2Hop.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public com.hps.july.trailcom.beans.Hop getHopid() throws java.rmi.RemoteException, javax.ejb.FinderException {
	return (com.hps.july.trailcom.beans.Hop)this.getHopidLink().value();
}
/**
 * This method was generated for supporting the association named RRLHops2Hop.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public com.hps.july.trailcom.beans.HopKey getHopidKey() {
	com.hps.july.trailcom.beans.HopKey temp = null;
	temp = new com.hps.july.trailcom.beans.HopKey();
	boolean hopid_NULLTEST = true;
	hopid_NULLTEST &= (hopid_hopsid == null);
	temp.hopsid = ((hopid_hopsid == null) ? 0 : hopid_hopsid.intValue());
	if (hopid_NULLTEST) temp = null;
	return temp;
}
/**
 * This method was generated for supporting the association named RRLHops2Hop.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
protected com.ibm.ivj.ejb.associations.interfaces.SingleLink getHopidLink() {
	if (hopidLink == null)
		hopidLink = new RRLHops2ToHopidLink(this);
	return hopidLink;
}
/**
 * Getter method for number_in_file
 * @return java.lang.Integer
 */
public java.lang.Integer getNumber_in_file() {
	return number_in_file;
}
/**
 * Getter method for power_a
 * @return java.lang.Double
 */
public java.math.BigDecimal getPower_a() {
	return power_a;
}
/**
 * Getter method for power_b
 * @return java.lang.Double
 */
public java.math.BigDecimal getPower_b() {
	return power_b;
}
/**
 * Getter method for power_doc
 */
public java.math.BigDecimal getPower_doc() {
	return power_doc;
}
/**
 * Getter method for resource_doc
 */
public java.lang.Integer getResource_doc() {
	return resource_doc;
}
/**
 * Getter method for sfonumber
 */
public java.lang.String getSfonumber() {
	return sfonumber;
}
/**
 * Getter method for signal_calc_a
 * @return java.lang.Double
 */
public java.math.BigDecimal getSignal_calc_a() {
	return signal_calc_a;
}
/**
 * Getter method for signal_calc_b
 * @return java.lang.Double
 */
public java.math.BigDecimal getSignal_calc_b() {
	return signal_calc_b;
}
/**
 * Getter method for signal_real_a
 * @return java.lang.Double
 */
public java.math.BigDecimal getSignal_real_a() {
	return signal_real_a;
}
/**
 * Getter method for signal_real_b
 * @return java.lang.Double
 */
public java.math.BigDecimal getSignal_real_b() {
	return signal_real_b;
}
/**
 * Getter method for speed_doc
 */
public java.lang.String getSpeed_doc() {
	return speed_doc;
}
/**
 * Getter method for type_hw
 * @return java.lang.String
 */
public java.lang.String getType_hw() {
	return type_hw;
}
/**
 * This method was generated for supporting the association named RRLHops2Hop.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void privateSetHopidKey(com.hps.july.trailcom.beans.HopKey inKey) {
	boolean hopid_NULLTEST = (inKey == null);
	if (hopid_NULLTEST) hopid_hopsid = null; else hopid_hopsid = (new Integer(inKey.hopsid));
}
/**
 * Setter method for accumid_a
 * @param newValue java.lang.Integer
 */
public void setAccumid_a(java.lang.Integer newValue) {
	this.accumid_a = newValue;
}
/**
 * Setter method for accumid_b
 * @param newValue java.lang.Integer
 */
public void setAccumid_b(java.lang.Integer newValue) {
	this.accumid_b = newValue;
}
/**
 * Setter method for azimuth
 * @param newValue java.lang.Double
 */
public void setAzimuth(java.math.BigDecimal newValue) {
	this.azimuth = newValue;
}
/**
 * Setter method for azimuthAB_Doc
 */
public void setAzimuthAB_Doc(java.math.BigDecimal newValue) {
	this.azimuthAB_Doc = newValue;
}
/**
 * Setter method for azimuthBA_Doc
 */
public void setAzimuthBA_Doc(java.math.BigDecimal newValue) {
	this.azimuthBA_Doc = newValue;
}
/**
 * Setter method for cable_2mb_a
 * @param newValue java.lang.Double
 */
public void setCable_2mb_a(java.math.BigDecimal newValue) {
	this.cable_2mb_a = newValue;
}
/**
 * Setter method for cable_2mbr_b
 * @param newValue java.lang.Double
 */
public void setCable_2mbr_b(java.math.BigDecimal newValue) {
	this.cable_2mbr_b = newValue;
}
/**
 * Setter method for cable_power_a
 * @param newValue java.lang.Double
 */
public void setCable_power_a(java.math.BigDecimal newValue) {
	this.cable_power_a = newValue;
}
/**
 * Setter method for cable_power_b
 * @param newValue java.lang.Double
 */
public void setCable_power_b(java.math.BigDecimal newValue) {
	this.cable_power_b = newValue;
}
/**
 * Setter method for cable_rrl_a
 * @param newValue java.lang.Double
 */
public void setCable_rrl_a(java.math.BigDecimal newValue) {
	this.cable_rrl_a = newValue;
}
/**
 * Setter method for cable_rrl_b
 * @param newValue java.lang.Double
 */
public void setCable_rrl_b(java.math.BigDecimal newValue) {
	this.cable_rrl_b = newValue;
}
/**
 * Setter method for capacity
 */
public void setCapacity(java.lang.Integer newValue) {
	this.capacity = newValue;
}
/**
 * Setter method for comment_a
 * @param newValue java.lang.String
 */
public void setComment_a(java.lang.String newValue) {
	this.comment_a = newValue;
}
/**
 * Setter method for comment_b
 * @param newValue java.lang.String
 */
public void setComment_b(java.lang.String newValue) {
	this.comment_b = newValue;
}
/**
 * Setter method for comment_doc
 */
public void setComment_doc(java.lang.String newValue) {
	this.comment_doc = newValue;
}
/**
 * Setter method for diam_a
 * @param newValue java.lang.Double
 */
public void setDiam_a(java.math.BigDecimal newValue) {
	this.diam_a = newValue;
}
/**
 * Setter method for diam_a_doc
 */
public void setDiam_a_doc(java.math.BigDecimal newValue) {
	this.diam_a_doc = newValue;
}
/**
 * Setter method for diam_b
 * @param newValue java.lang.Double
 */
public void setDiam_b(java.math.BigDecimal newValue) {
	this.diam_b = newValue;
}
/**
 * Setter method for diam_b_doc
 */
public void setDiam_b_doc(java.math.BigDecimal newValue) {
	this.diam_b_doc = newValue;
}
/**
 * Setter method for diam2_a
 */
public void setDiam2_a(java.math.BigDecimal newValue) {
	this.diam2_a = newValue;
}
/**
 * Setter method for diam2_b
 */
public void setDiam2_b(java.math.BigDecimal newValue) {
	this.diam2_b = newValue;
}
/**
 * setEntityContext method comment
 * @param ctx javax.ejb.EntityContext
 * @exception java.rmi.RemoteException The exception description.
 */
public void setEntityContext(javax.ejb.EntityContext ctx) throws java.rmi.RemoteException {
	entityContext = ctx;
}
/**
 * Setter method for file_number
 * @param newValue java.lang.Integer
 */
public void setFile_number(java.lang.Integer newValue) {
	this.file_number = newValue;
}
/**
 * Setter method for file_shortnumber
 * @param newValue java.lang.Integer
 */
public void setFile_shortnumber(java.lang.Integer newValue) {
	this.file_shortnumber = newValue;
}
/**
 * Setter method for frequency_a_doc
 */
public void setFrequency_a_doc(java.math.BigDecimal newValue) {
	this.frequency_a_doc = newValue;
}
/**
 * Setter method for frequency_a1
 * @param newValue java.lang.Double
 */
public void setFrequency_a1(java.math.BigDecimal newValue) {
	this.frequency_a1 = newValue;
}
/**
 * Setter method for frequency_a2
 * @param newValue java.lang.Double
 */
public void setFrequency_a2(java.math.BigDecimal newValue) {
	this.frequency_a2 = newValue;
}
/**
 * Setter method for frequency_b_doc
 */
public void setFrequency_b_doc(java.math.BigDecimal newValue) {
	this.frequency_b_doc = newValue;
}
/**
 * Setter method for frequency_b1
 * @param newValue java.lang.Double
 */
public void setFrequency_b1(java.math.BigDecimal newValue) {
	this.frequency_b1 = newValue;
}
/**
 * Setter method for frequency_b2
 * @param newValue java.lang.Double
 */
public void setFrequency_b2(java.math.BigDecimal newValue) {
	this.frequency_b2 = newValue;
}
/**
 * Setter method for height_a
 * @param newValue java.lang.Double
 */
public void setHeight_a(java.math.BigDecimal newValue) {
	this.height_a = newValue;
}
/**
 * Setter method for height_a_doc
 */
public void setHeight_a_doc(java.math.BigDecimal newValue) {
	this.height_a_doc = newValue;
}
/**
 * Setter method for height_b
 * @param newValue java.lang.Double
 */
public void setHeight_b(java.math.BigDecimal newValue) {
	this.height_b = newValue;
}
/**
 * Setter method for height_b_doc
 */
public void setHeight_b_doc(java.math.BigDecimal newValue) {
	this.height_b_doc = newValue;
}
/**
 * This method was generated for supporting the association named RRLHops2Hop.  
 * 	It will be deleted/edited when the association is deleted/edited.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
public void setHopid(com.hps.july.trailcom.beans.Hop aHopid) throws java.rmi.RemoteException {
	this.getHopidLink().set(aHopid);
}
/**
 * Setter method for number_in_file
 * @param newValue java.lang.Integer
 */
public void setNumber_in_file(java.lang.Integer newValue) {
	this.number_in_file = newValue;
}
/**
 * Setter method for power_a
 * @param newValue java.lang.Double
 */
public void setPower_a(java.math.BigDecimal newValue) {
	this.power_a = newValue;
}
/**
 * Setter method for power_b
 * @param newValue java.lang.Double
 */
public void setPower_b(java.math.BigDecimal newValue) {
	this.power_b = newValue;
}
/**
 * Setter method for power_doc
 */
public void setPower_doc(java.math.BigDecimal newValue) {
	this.power_doc = newValue;
}
/**
 * Setter method for resource_doc
 */
public void setResource_doc(java.lang.Integer newValue) {
	this.resource_doc = newValue;
}
/**
 * Setter method for sfonumber
 */
public void setSfonumber(java.lang.String newValue) {
	this.sfonumber = newValue;
}
/**
 * Setter method for signal_calc_a
 * @param newValue java.lang.Double
 */
public void setSignal_calc_a(java.math.BigDecimal newValue) {
	this.signal_calc_a = newValue;
}
/**
 * Setter method for signal_calc_b
 * @param newValue java.lang.Double
 */
public void setSignal_calc_b(java.math.BigDecimal newValue) {
	this.signal_calc_b = newValue;
}
/**
 * Setter method for signal_real_a
 * @param newValue java.lang.Double
 */
public void setSignal_real_a(java.math.BigDecimal newValue) {
	this.signal_real_a = newValue;
}
/**
 * Setter method for signal_real_b
 * @param newValue java.lang.Double
 */
public void setSignal_real_b(java.math.BigDecimal newValue) {
	this.signal_real_b = newValue;
}
/**
 * Setter method for speed_doc
 */
public void setSpeed_doc(java.lang.String newValue) {
	this.speed_doc = newValue;
}
/**
 * Setter method for type_hw
 * @param newValue java.lang.String
 */
public void setType_hw(java.lang.String newValue) {
	this.type_hw = newValue;
}
/**
 * unsetEntityContext method comment
 * @exception java.rmi.RemoteException The exception description.
 */
public void unsetEntityContext() throws java.rmi.RemoteException {
	entityContext = null;
}
}
